// Products
export const REQUEST_SHOP = 'REQUEST_SHOP';
export const RECEIVED_SHOP_SUCCESS = 'RECEIVED_SHOP_SUCCESS';
export const RECEIVED_SHOP_FAILURE = 'RECEIVED_SHOP_FAILURE';
export const GET_PRODUCTS_BY_GROUP = 'GET_PRODUCTS_BY_GROUP';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';

// Cart
export const REQUEST_CART = 'REQUEST_CART';
export const RECEIVED_CART_SUCCESS = 'RECEIVED_CART_SUCCESS';
export const RECEIVED_CART_FAILURE = 'RECEIVED_CART_FAILURE';
export const GET_CART = 'GET_CART';
export const ADD = 'ADD';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE = 'REMOVE';
export const CHECKOUT = 'CHECKOUT';

// Sort
export const SET_SORT = 'SET_SORT';

// User
export const CHECK_USER_AUTH = 'CHECK_USER_AUTH';
export const USER_AUTH = 'USER_AUTH';
export const USER_UNKNOWN = 'USER_UNKNOWN';
export const REQUEST_REG = 'REQUEST_REG';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const REQUEST_LOGIN_FORGOT = 'REQUEST_LOGIN_FORGOT';
export const REQUEST_EDIT = 'REQUEST_EDIT';
export const REG_SUCCESS = 'REG_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_FORGOT_SUCCESS = 'LOGIN_FORGOT_SUCCESS';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const REG_FAILURE = 'REG_FAILURE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGIN_FORGOT_FAILURE = 'LOGIN_FORGOT_FAILURE';
export const EDIT_FAILURE = 'EDIT_FAILURE';

// Search
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const GET_SEARCH_ITEMS = 'GET_SEARCH_ITEMS';
export const RECEIVED_SEARCH_ITEMS_SUCCESS = 'RECEIVED_SEARCH_ITEMS_SUCCESS';
export const RECEIVED_SEARCH_ITEMS_FAILURE = 'RECEIVED_SEARCH_ITEMS_FAILURE';

// Preloader
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
